version: '3'
services:
  server:
    image: node:18-alpine
    volumes:
      - ./node_modules:/node_modules
      - ./package.json:/package.json
      - ./tsconfig.json:/tsconfig.json
      - ./src:/src
      - ./public:/public
      - ./lib1.ts:/lib1.ts
    ports:
      - 3000:3000
      - 9229:9229
    command: yarn nodemon --signal SIGINT --inspect=0.0.0.0:9229 --nolazy src/server.ts

  app2:
    image: node:18-alpine
    volumes:
      - ./node_modules:/node_modules
      - ./package.json:/package.json
      - ./tsconfig.json:/tsconfig.json
      - ./app2.ts:/app2.ts
      - ./lib1.ts:/lib1.ts
    ports:
      - 3001:3000
      - 9230:9229
    command: yarn nodemon --signal SIGINT --inspect=0.0.0.0:9229 --nolazy app2.ts
