name: test
on: [push, pull_request]
jobs:
  integration-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Dummy test
        run: echo "Dummy test"
